version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: PietroWei
      POSTGRES_PASSWORD: Gionniwei98@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  init_db:
    build: .
    command: /app/init_db.sh
    depends_on:
      - db
    environment:
      DB_NAME: customer_db
      DB_USER: PietroWei
      DB_PASSWORD: Gionniwei98@
      DB_HOST: db
      DB_PORT: 5432

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
      - init_db
    environment:
      DB_NAME: customer_db
      DB_USER: PietroWei
      DB_PASSWORD: Gionniwei98@
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: